AISDK-53: Run integration tests on different environments based on branch name
revdotcom/revai-node-sdk pull request #13
Opened 2019-07-09 19:55 UTC by kbridbur

2019-07-09 19:56 UTC, kbridbur commented on .travis.yml
> +      script: npm run test
These scripts will change to be whatever we run to run the integration tests once those are done

2019-07-09 19:57 UTC, kbridbur commented on .travis.yml
> +  include:
Defines a list of jobs to be executed after the main script

2019-07-09 19:57 UTC, kbridbur commented on .travis.yml
> +      if: branch =~ /^feature/
stage is only run if the condition is satisfied

2019-07-09 19:58 UTC, kbridbur commented on .travis.yml
> +        secure: "Wl6dUEMeU0O34XrsJE04CysZhb4o8d/2taFGAgEBGfIpeS9mlqQJKFOIeXbbBqZsdK0WKVLPpi6IINfnag8kcymyShfLZUvGxzOpqhIWL4TGDOa1YwwiirDgQhhuRob+V13BURNdCWDwaNMVpHvZW45ickTVVaz8m7h9FTlxrljkSa+8KPxBGD
Api key and base url encrypted using travis cli

2019-07-10 19:16 UTC, amikofalvy commented on .travis.yml
> +      if: branch = master
As we discussed in slack, we don't use the master branch.

We should instead map such as the following:
```
if: tag =~ /*.*.*/ -> prod
if: branch = develop & tag != ~ /*.*.*/ -> stage
if: branch =~ /^feature/ -> test
```

2019-07-10 19:31 UTC, amikofalvy requested changes
see comments inline

2019-09-04 21:35 UTC, kbridbur commented on .travis.yml
> +        - npm run build
We unfortunately need to re-run build because travis doesn't keep anything in between stages

2019-09-04 22:06 UTC, kbridbur commented on .travis.yml
> +    - stage: build
travis requires separate stages for separate versions

2019-09-04 23:20 UTC, amikofalvy approved these changes
Looks good.

2019-09-04 23:23 UTC, merged