AISDK-168: Add transcriber and start ts
revdotcom/revai-node-sdk pull request #77
Opened 2022-01-26 05:42 UTC by Chanc3

2022-01-26 18:30 UTC, amikofalvy requested changes
Changes look good, but we need to bump the version

2022-01-26 18:34 UTC, amikofalvy commented
Also, we might want to add integration tests for the new streaming and async job parameters

2022-01-26 19:06 UTC, kbridbur commented on examples/streaming_transcribe_from_local_file.js
> +    "machine_v2" /* (optional) transcriber */
This should not be the default. streaming v2 is in closed beta

2022-01-26 19:07 UTC, kbridbur requested changes
Streaming example should not use machine_v2

2022-01-26 19:36 UTC, k-weng requested changes

2022-01-26 19:36 UTC, k-weng commented on src/models/RevAiApiJob.ts
> +    custom_vocabulary_id?:string;
```suggestion
    filter_profanity?: boolean;
    custom_vocabulary_id?: string;
```

2022-01-26 19:36 UTC, k-weng commented on test/unit/api-client/api-client.submit.spec.ts
> +                transcriber: null
```suggestion
	        language: null,
                transcriber: null
```

2022-01-26 19:36 UTC, k-weng commented on examples/async_transcribe_media_from_url.js
> +        transcriber: "machine_v2"
Add a comment here

2022-01-26 19:36 UTC, k-weng commented on examples/async_transcribe_local_media_file.js
> +        transcriber: "machine_v2"
Add a comment here

2022-01-26 19:37 UTC, k-weng commented
> Changes look good, but we need to bump the version

@amikofalvy I think we can release all of this under `3.0.0` so no need to bump version

2022-01-27 00:13 UTC, amikofalvy approved these changes

2022-01-27 04:00 UTC, k-weng approved these changes

2022-01-27 15:48 UTC, kbridbur approved these changes

2022-01-27 15:59 UTC, merged